# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1532aca32d1ddac075fb88830520f9d2bf0cb2df09dfd9cb1716c5d1dc7b724d5392f1432e3cf241f179efd85d5a1caeb9fe4759b2256feaed1c337ecd446110

test:
  secret_key_base: 45da5c0cf12a708bfe13a9b4c078829277113b554f2b8cf0f5c019401b00dd54f82986a40b1a1227f1e51b46222b556ae09a9830476f884cf98dc11bb3ce5e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 45da5c0cf12a708bfe13a9b4c078829277113b554f2b8cf0f5c019401b00dd54f82986a40b1a1227f1e51b46222b556ae09a9830476f884cf98dc11bb3ce5e0a
